Repository invisible-hands/backend, pull requests merged in 2023-10, with the labels that each got.

#6 Feat swagger jsj
  src/main/java/com/betting/ground/auction/controller/AuctionController.java
  src/main/java/com/betting/ground/auction/domain/Auction.java
  src/main/java/com/betting/ground/auction/dto/AuctionImageDto.java
  src/main/java/com/betting/ground/auction/dto/ItemResponse.java
  src/main/java/com/betting/ground/auction/dto/NewItemDto.java
  src/main/java/com/betting/ground/auction/service/AuctionService.java
  src/main/java/com/betting/ground/config/SecurityConfig.java
Labels: 백엔드, 정상준

#7 API 문서화 #5
  build.gradle
  src/main/java/com/betting/ground/auction/controller/AuctionController.java
  src/main/java/com/betting/ground/auction/domain/request/AuctionCreateRequest.java
  src/main/java/com/betting/ground/auction/domain/request/BidRequest.java
  src/main/java/com/betting/ground/auction/domain/response/AuctionInfo.java
  src/main/java/com/betting/ground/auction/domain/response/SearchResponse.java
  src/main/java/com/betting/ground/common/MultipartJackson2HttpMessageConverter.java
  src/main/java/com/betting/ground/common/dto/Response.java
  src/main/java/com/betting/ground/common/exception/ExceptionController.java
Labels: 백엔드, 최하록

#8 [feat] api 문서화 by 판준 #5
  src/main/java/com/betting/ground/auction/controller/AuctionController.java
  src/main/java/com/betting/ground/auction/controller/SellerInfo.java
  src/main/java/com/betting/ground/auction/domain/dto/AuctionImageDto.java
  src/main/java/com/betting/ground/auction/domain/dto/BidHistoryDto.java
  src/main/java/com/betting/ground/auction/domain/dto/BidInfo.java
  src/main/java/com/betting/ground/auction/domain/dto/ItemDetailDto.java
  src/main/java/com/betting/ground/auction/domain/dto/TagDto.java
  src/main/java/com/betting/ground/auction/domain/dto/biddingItemDto.java
Labels: 권판준, 백엔드

#14 [feat] 경매 등록 api 수정 #5
  src/main/java/com/betting/ground/auction/dto/request/AuctionCreateRequest.java
Labels: 권판준, 백엔드

#24 [feat] swagger api 수정 #5
  src/main/java/com/betting/ground/auction/dto/SellerInfo.java
Labels: 권판준, 백엔드

#26 [Feat] api 수정
  src/main/java/com/betting/ground/auction/controller/AuctionController.java
  src/main/java/com/betting/ground/auction/dto/AuctionDetailInfo.java
  src/main/java/com/betting/ground/auction/dto/ItemDetailDto.java
  src/main/java/com/betting/ground/auction/dto/response/AuctionInfo.java
  src/main/java/com/betting/ground/auction/dto/response/ItemDetailDto.java
  src/main/java/com/betting/ground/auction/repository/AuctionRepositoryImpl.java
  src/main/java/com/betting/ground/common/HealthController.java
Labels: 백엔드, 정상준

#23 [Feat] 일부 api response 수정 #5
  src/main/java/com/betting/ground/auction/dto/response/BidInfoResponse.java
  src/main/java/com/betting/ground/deal/controller/DealController.java
  src/main/java/com/betting/ground/deal/dto/response/BiddingInfo.java
  src/main/java/com/betting/ground/deal/dto/response/BiddingInfoResponse.java
  src/main/java/com/betting/ground/deal/dto/response/BiddingStatusCnt.java
  src/main/java/com/betting/ground/deal/dto/response/DealCountResponse.java
  src/main/java/com/betting/ground/deal/dto/response/PurchaseInfo.java
  src/main/java/com/betting/ground/deal/dto/response/PurchaseInfoResponse.java
  src/main/java/com/betting/ground/deal/dto/response/PurchaseStatusCnt.java
  src/main/java/com/betting/ground/deal/dto/response/SalesInfo.java
  src/main/java/com/betting/ground/deal/dto/response/SalesInfoResponse.java
  src/main/java/com/betting/ground/deal/dto/response/SalesStatusCnt.java
Labels: 백엔드, 최하록

#30 [feat] 카카오 로그인 api #18
  build.gradle
  src/main/java/com/betting/ground/RefreshToken/domain/RefreshToken.java
  src/main/java/com/betting/ground/RefreshToken/repository/RefreshTokenRepository.java
  src/main/java/com/betting/ground/auction/controller/AuctionController.java
  src/main/java/com/betting/ground/common/exception/ErrorCode.java
  src/main/java/com/betting/ground/config/CustomAuthenticationEntryPoint.java
  src/main/java/com/betting/ground/config/SecurityConfig.java
  src/main/java/com/betting/ground/config/filter/JwtTokenFilter.java
  src/main/java/com/betting/ground/config/jwt/JwtProperties.java
  src/main/java/com/betting/ground/config/jwt/JwtUtils.java
  src/main/java/com/betting/ground/user/controller/UserController.java
  src/main/java/com/betting/ground/user/domain/User.java
  src/main/java/com/betting/ground/user/dto/LoginResponseDto.java
  src/main/java/com/betting/ground/user/dto/ReissueRequestDto.java
  src/main/java/com/betting/ground/user/dto/login/KakaoProfile.java
  src/main/java/com/betting/ground/user/dto/login/LoginUser.java
  src/main/java/com/betting/ground/user/dto/login/OAuthToken.java
  src/main/java/com/betting/ground/user/dto/login/UserDetailServiceImpl.java
  src/main/java/com/betting/ground/user/repository/UserRepository.java
  src/main/java/com/betting/ground/user/service/UserService.java
  src/main/resources/static/image/kakao_login_large_narrow.png
  src/main/resources/static/index.html
Labels: 권판준, 백엔드

#43 [Feat] 마이페이지 프로필 API 구현완료
  src/main/java/com/betting/ground/GroundApplication.java
  src/main/java/com/betting/ground/auction/repository/AuctionRepositoryImpl.java
  src/main/java/com/betting/ground/common/exception/ErrorCode.java
  src/main/java/com/betting/ground/user/controller/UserController.java
  src/main/java/com/betting/ground/user/domain/Address.java
  src/main/java/com/betting/ground/user/domain/Bank.java
  src/main/java/com/betting/ground/user/domain/User.java
  src/main/java/com/betting/ground/user/dto/UserAccountDTO.java
  src/main/java/com/betting/ground/user/dto/UserAddressDTO.java
  src/main/java/com/betting/ground/user/dto/UserDTO.java
  src/main/java/com/betting/ground/user/dto/UserNicknameDTO.java
  src/main/java/com/betting/ground/user/repository/UserRepository.java
  src/main/java/com/betting/ground/user/service/UserService.java
Labels: 백엔드, 차진우

#42 Feat auction seller info
  build.gradle
  src/main/java/com/betting/ground/GroundApplication.java
  src/main/java/com/betting/ground/auction/controller/AuctionController.java
  src/main/java/com/betting/ground/auction/domain/Auction.java
  src/main/java/com/betting/ground/auction/domain/AuctionImage.java
  src/main/java/com/betting/ground/auction/domain/Tag.java
  src/main/java/com/betting/ground/auction/dto/BiddingItemDto.java
  src/main/java/com/betting/ground/auction/dto/SellerInfo.java
  src/main/java/com/betting/ground/auction/dto/biddingItemDto.java
  src/main/java/com/betting/ground/auction/dto/request/AuctionCreateRequest.java
  src/main/java/com/betting/ground/auction/repository/AuctionRepositoryCustom.java
  src/main/java/com/betting/ground/auction/repository/AuctionRepositoryImpl.java
  src/main/java/com/betting/ground/auction/service/AuctionService.java
  src/main/java/com/betting/ground/config/s3/S3Config.java
  src/main/java/com/betting/ground/user/controller/UserController.java
  src/main/java/com/betting/ground/user/service/UserService.java
  src/main/resources/static/index.html
Labels: 권판준, 백엔드

#41 [feat] 입찰 내역 api 구현 완료
  src/main/java/com/betting/ground/auction/controller/AuctionController.java
  src/main/java/com/betting/ground/auction/domain/BidHistory.java
  src/main/java/com/betting/ground/auction/dto/BidHistoryDto.java
  src/main/java/com/betting/ground/auction/dto/BidInfo.java
  src/main/java/com/betting/ground/auction/repository/BidHistoryRepository.java
  src/main/java/com/betting/ground/auction/repository/BidHistoryRepositoryCustom.java
  src/main/java/com/betting/ground/auction/repository/BidHistoryRepositoryImpl.java
  src/main/java/com/betting/ground/auction/service/AuctionService.java
Labels: 권판준, 백엔드

#38 Feat auction delete
  src/main/java/com/betting/ground/auction/controller/AuctionController.java
  src/main/java/com/betting/ground/auction/repository/AuctionImageRepository.java
  src/main/java/com/betting/ground/auction/repository/AuctionImageRepositoryCustom.java
  src/main/java/com/betting/ground/auction/repository/AuctionImageRepositoryImpl.java
  src/main/java/com/betting/ground/auction/repository/TagRepository.java
  src/main/java/com/betting/ground/auction/repository/TagRepositoryCustom.java
  src/main/java/com/betting/ground/auction/repository/TagRepositoryImpl.java
  src/main/java/com/betting/ground/auction/service/AuctionService.java
Labels: 권판준, 백엔드

#44 [Feat] 경매 상세 조회 인증 유저 수정
  k8s/configs/init.sql
  k8s/deployment.yaml
  k8s/kustomization.yaml
  k8s/scheduler.yaml
  src/main/java/com/betting/ground/auction/controller/AuctionController.java
  src/main/java/com/betting/ground/auction/repository/AuctionRepositoryCustom.java
  src/main/java/com/betting/ground/auction/repository/AuctionRepositoryImpl.java
  src/main/java/com/betting/ground/auction/service/AuctionService.java
Labels: 백엔드, 정상준

#35 [Feat] 마이페이지 조회 리스트 구현
  src/main/java/com/betting/ground/admin/domain/Settlement.java
  src/main/java/com/betting/ground/auction/controller/AuctionController.java
  src/main/java/com/betting/ground/auction/dto/response/BidInfoResponse.java
  src/main/java/com/betting/ground/auction/repository/AuctionRepositoryCustom.java
  src/main/java/com/betting/ground/auction/repository/AuctionRepositoryImpl.java
  src/main/java/com/betting/ground/auction/service/AuctionService.java
  src/main/java/com/betting/ground/common/exception/ErrorCode.java
  src/main/java/com/betting/ground/deal/controller/DealController.java
  src/main/java/com/betting/ground/deal/domain/Deal.java
  src/main/java/com/betting/ground/deal/dto/response/BiddingInfo.java
  src/main/java/com/betting/ground/deal/dto/response/BiddingInfoResponse.java
  src/main/java/com/betting/ground/deal/dto/response/DealCountResponse.java
  src/main/java/com/betting/ground/deal/dto/response/PurchaseInfo.java
  src/main/java/com/betting/ground/deal/dto/response/PurchaseInfoResponse.java
  src/main/java/com/betting/ground/deal/dto/response/SalesInfo.java
  src/main/java/com/betting/ground/deal/dto/response/SalesInfoResponse.java
  src/main/java/com/betting/ground/deal/repository/DealRepository.java
  src/main/java/com/betting/ground/deal/repository/DealRepositoryCustom.java
  src/main/java/com/betting/ground/deal/repository/DealRepositoryImpl.java
  src/main/java/com/betting/ground/deal/service/DealService.java
  src/main/java/com/betting/ground/delivery/controller/DeliveryController.java
  src/main/java/com/betting/ground/delivery/domain/Delivery.java
  src/main/java/com/betting/ground/delivery/dto/request/DeliveryInfoRequest.java
  src/main/java/com/betting/ground/delivery/dto/response/DeliveryInfoResponse.java
  src/main/java/com/betting/ground/delivery/service/DeliveryService.java
  src/main/java/com/betting/ground/kakaopay/controller/KakaoPayController.java
  src/main/java/com/betting/ground/kakaopay/dto/request/KakaoReadyRequest.java
  src/main/java/com/betting/ground/kakaopay/dto/response/Amount.java
  src/main/java/com/betting/ground/kakaopay/dto/response/KakaoApproveResponse.java
  src/main/java/com/betting/ground/kakaopay/dto/response/KakaoReadyResponse.java
  src/main/java/com/betting/ground/kakaopay/service/KakaoPayService.java
  src/main/java/com/betting/ground/user/domain/Payment.java
  src/main/java/com/betting/ground/user/domain/User.java
  src/main/java/com/betting/ground/user/repository/UserRepositoryCustom.java
  src/main/java/com/betting/ground/user/repository/UserRepositoryImpl.java
  src/main/java/com/betting/ground/user/service/UserService.java
Labels: 백엔드, 최하록
