Repository invisible-hands/backend, pull requests merged in 2023-11, with the labels that each got.

#56 [refactor] User Service 부분 리팩토링
  src/main/java/com/betting/ground/user/controller/UserController.java
  src/main/java/com/betting/ground/user/dto/UserDTO.java
  src/main/java/com/betting/ground/user/service/UserService.java
Labels: 백엔드, 차진우

#55 [refactor] 코드 정리
  src/main/java/com/betting/ground/auction/controller/AuctionController.java
  src/main/java/com/betting/ground/auction/dto/AuctionDetailInfo.java
  src/main/java/com/betting/ground/auction/dto/response/AuctionInfo.java
  src/main/java/com/betting/ground/auction/repository/AuctionRepositoryImpl.java
  src/main/java/com/betting/ground/auction/service/AuctionService.java
Labels: 백엔드, 정상준

#61 [refacotr] 입찰 내역 보기 api 리펙토링 #52
  src/main/java/com/betting/ground/auction/dto/BidHistoryDto.java
  src/main/java/com/betting/ground/auction/service/AuctionService.java
Labels: 권판준, 백엔드

#58 [refactor] 판매자 정보 api 리팩토링 #50
  src/main/java/com/betting/ground/auction/dto/SellerInfo.java
  src/main/java/com/betting/ground/auction/dto/SellerItemDto.java
  src/main/java/com/betting/ground/auction/repository/AuctionRepositoryCustom.java
  src/main/java/com/betting/ground/auction/repository/AuctionRepositoryImpl.java
  src/main/java/com/betting/ground/auction/service/AuctionService.java
Labels: 권판준, 백엔드

#60 Refactor auction delete
  src/main/java/com/betting/ground/auction/service/AuctionService.java
  src/main/java/com/betting/ground/common/exception/ErrorCode.java
Labels: 권판준, 백엔드

#57 Refactor kakao login
  src/main/java/com/betting/ground/RefreshToken/domain/RefreshToken.java
  src/main/java/com/betting/ground/user/controller/UserController.java
  src/main/java/com/betting/ground/user/domain/User.java
  src/main/java/com/betting/ground/user/dto/LoginResponseDto.java
  src/main/java/com/betting/ground/user/service/UserService.java
Labels: 권판준, 백엔드

#59 Refactor auction create
  src/main/java/com/betting/ground/auction/domain/Auction.java
  src/main/java/com/betting/ground/auction/domain/AuctionImage.java
  src/main/java/com/betting/ground/auction/domain/Tag.java
  src/main/java/com/betting/ground/auction/service/AuctionService.java
  src/main/java/com/betting/ground/common/s3/S3Utils.java
Labels: 권판준, 백엔드

#64 [feat] api 구현 및 동시성 다루기
  src/main/java/com/betting/ground/admin/domain/Settlement.java
  src/main/java/com/betting/ground/admin/repository/SettlementRepository.java
  src/main/java/com/betting/ground/auction/controller/AuctionController.java
  src/main/java/com/betting/ground/auction/domain/Auction.java
  src/main/java/com/betting/ground/auction/domain/BidHistory.java
  src/main/java/com/betting/ground/auction/dto/request/PayRequest.java
  src/main/java/com/betting/ground/auction/repository/AuctionRepository.java
  src/main/java/com/betting/ground/auction/repository/BidHistoryRepository.java
  src/main/java/com/betting/ground/auction/service/AuctionService.java
  src/main/java/com/betting/ground/common/exception/ErrorCode.java
  src/main/java/com/betting/ground/deal/domain/Deal.java
  src/main/java/com/betting/ground/deal/service/DealService.java
  src/main/java/com/betting/ground/user/domain/Payment.java
  src/main/java/com/betting/ground/user/domain/PaymentType.java
  src/main/java/com/betting/ground/user/domain/User.java
  src/main/java/com/betting/ground/user/repository/UserRepository.java
  src/test/java/com/betting/ground/auction/service/AuctionServiceTest.java
Labels: 권판준, 백엔드, 정상준, 최하록

#63 [Feat] 조회수 동시성 다루기
  build.gradle
  k8s/scheduler.yaml
  src/main/java/com/betting/ground/auction/controller/AuctionController.java
  src/main/java/com/betting/ground/auction/domain/Auction.java
  src/main/java/com/betting/ground/auction/domain/View.java
  src/main/java/com/betting/ground/auction/repository/AuctionRepositoryImpl.java
  src/main/java/com/betting/ground/auction/repository/ViewCacheRepository.java
  src/main/java/com/betting/ground/auction/repository/ViewRepository.java
  src/main/java/com/betting/ground/auction/service/AuctionService.java
  src/main/java/com/betting/ground/common/exception/ExceptionController.java
  src/main/java/com/betting/ground/common/scheduler/SchedulerController.java
  src/main/java/com/betting/ground/config/RedisConfig.java
  src/main/java/com/betting/ground/config/RestTemplateConfig.java
  src/main/java/com/betting/ground/kakaopay/controller/KakaoPayController.java
  src/main/java/com/betting/ground/kakaopay/service/KakaoPayService.java
  src/test/java/com/betting/ground/auction/repository/ViewCacheRepositoryTest.java
  src/test/java/com/betting/ground/auction/service/AuctionServiceTest.java
Labels: 권판준, 백엔드, 정상준, 최하록

#71 [refactor] 판매자 정보 api 수정
  src/main/java/com/betting/ground/auction/dto/SellerItemDto.java
  src/main/java/com/betting/ground/auction/repository/AuctionRepositoryCustom.java
  src/main/java/com/betting/ground/auction/repository/AuctionRepositoryImpl.java
  src/main/java/com/betting/ground/auction/service/AuctionService.java
Labels: 권판준, 백엔드

#69 [Refactor] 조회 api 응답 수정 및 deal에 대한 스케줄 추가
  k8s/scheduler.yaml
  src/main/java/com/betting/ground/auction/controller/AuctionController.java
  src/main/java/com/betting/ground/auction/dto/AuctionDetailInfo.java
  src/main/java/com/betting/ground/auction/dto/response/AuctionInfo.java
  src/main/java/com/betting/ground/auction/repository/AuctionRepositoryImpl.java
  src/main/java/com/betting/ground/auction/service/AuctionService.java
  src/main/java/com/betting/ground/common/scheduler/SchedulerController.java
  src/main/java/com/betting/ground/deal/repository/DealRepository.java
  src/test/java/com/betting/ground/auction/service/AuctionServiceTest.java
Labels: 백엔드, 정상준

#68 refactor. 마이 페이지 리스트 수정, 상품 입찰페이지 조회 수정
  src/main/java/com/betting/ground/auction/dto/response/BidInfoResponse.java
  src/main/java/com/betting/ground/auction/repository/AuctionImageRepository.java
  src/main/java/com/betting/ground/auction/repository/AuctionRepositoryCustom.java
  src/main/java/com/betting/ground/auction/repository/AuctionRepositoryImpl.java
  src/main/java/com/betting/ground/auction/service/AuctionService.java
  src/main/java/com/betting/ground/deal/dto/response/BiddingInfo.java
  src/main/java/com/betting/ground/deal/dto/response/PurchaseInfo.java
  src/main/java/com/betting/ground/deal/dto/response/SalesInfo.java
  src/main/java/com/betting/ground/deal/repository/DealRepositoryImpl.java
Labels: 백엔드, 최하록

#74 [feat] 시큐리티 설정 #73
  src/main/java/com/betting/ground/GroundApplication.java
  src/main/java/com/betting/ground/auction/service/AuctionService.java
  src/main/java/com/betting/ground/config/SecurityConfig.java
  src/main/java/com/betting/ground/user/service/UserService.java
Labels: 권판준, 백엔드

#79 [Fix] 배송, 구매확정 api 수정
  src/main/java/com/betting/ground/common/exception/ErrorCode.java
  src/main/java/com/betting/ground/deal/service/DealService.java
  src/main/java/com/betting/ground/delivery/controller/DeliveryController.java
  src/main/java/com/betting/ground/delivery/service/DeliveryService.java
  src/main/java/com/betting/ground/user/domain/User.java
Labels: 백엔드, 최하록

#81 Refactor panjun
  src/main/java/com/betting/ground/auction/controller/AuctionController.java
  src/main/java/com/betting/ground/auction/service/AuctionService.java
  src/main/java/com/betting/ground/common/exception/ErrorCode.java
  src/main/java/com/betting/ground/config/SecurityConfig.java
  src/main/java/com/betting/ground/user/controller/UserController.java
  src/main/java/com/betting/ground/user/service/UserService.java
Labels: 권판준, 금방해유, 백엔드, 차진우

#86 [fix] 경매 생성 api 수정 #85
  src/main/java/com/betting/ground/auction/controller/AuctionController.java
  src/main/java/com/betting/ground/auction/domain/Auction.java
  src/main/java/com/betting/ground/auction/dto/CreateAuctionDto.java
  src/main/java/com/betting/ground/auction/dto/request/AuctionCreateRequest.java
  src/main/java/com/betting/ground/auction/service/AuctionService.java
  src/main/java/com/betting/ground/common/exception/ErrorCode.java
Labels: 권판준, 백엔드

#84 Fix security
  src/main/java/com/betting/ground/common/exception/ErrorCode.java
  src/main/java/com/betting/ground/config/CustomAccessDeniedHandler.java
  src/main/java/com/betting/ground/config/CustomAuthenticationEntryPoint.java
  src/main/java/com/betting/ground/config/SecurityConfig.java
Labels: 권판준, 백엔드

#92 fix. 경매 참여 목록 조회 쿼리 수정
  src/main/java/com/betting/ground/deal/domain/Deal.java
  src/main/java/com/betting/ground/deal/domain/DealStatus.java
  src/main/java/com/betting/ground/deal/repository/DealRepositoryImpl.java
Labels: 금방해유, 백엔드, 최하록

#94 Refactor jsj
  src/main/java/com/betting/ground/auction/controller/AuctionController.java
  src/main/java/com/betting/ground/auction/dto/SellerItemDto.java
  src/main/java/com/betting/ground/auction/repository/AuctionRepositoryCustom.java
  src/main/java/com/betting/ground/auction/repository/AuctionRepositoryImpl.java
  src/main/java/com/betting/ground/auction/service/AuctionService.java
  src/main/java/com/betting/ground/config/SecurityConfig.java
Labels: 백엔드, 정상준

#100 [Fix] 경매 참여 인원 쿼리 수정
  src/main/java/com/betting/ground/auction/repository/AuctionRepositoryImpl.java
Labels: 백엔드, 정상준

#103 [fix] 에러 코드 수정 #99
  src/main/java/com/betting/ground/auction/controller/AuctionController.java
  src/main/java/com/betting/ground/auction/service/AuctionService.java
  src/main/java/com/betting/ground/common/exception/ErrorCode.java
Labels: 권판준, 백엔드

#107 feat.구매 확정 대기 모음 api 추가
  src/main/java/com/betting/ground/auction/repository/AuctionRepositoryImpl.java
  src/main/java/com/betting/ground/deal/controller/DealController.java
  src/main/java/com/betting/ground/deal/repository/DealRepositoryCustom.java
  src/main/java/com/betting/ground/deal/repository/DealRepositoryImpl.java
  src/main/java/com/betting/ground/deal/service/DealService.java
Labels: 백엔드, 최하록

#108 feat. 구매 확정 대기 모음 api 추가
  src/main/java/com/betting/ground/auction/repository/AuctionRepositoryImpl.java
  src/main/java/com/betting/ground/deal/controller/DealController.java
  src/main/java/com/betting/ground/deal/repository/DealRepositoryCustom.java
  src/main/java/com/betting/ground/deal/repository/DealRepositoryImpl.java
  src/main/java/com/betting/ground/deal/service/DealService.java
Labels: 백엔드, 최하록

#109 [Fix] 구매 취소 시 환불 기능
  src/main/java/com/betting/ground/common/scheduler/SchedulerController.java
  src/main/java/com/betting/ground/user/repository/UserRepository.java
Labels: 백엔드, 정상준

#111 fix. cookie 수정
  src/main/java/com/betting/ground/auction/controller/AuctionController.java
Labels: 백엔드, 최하록
